version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          VERSION=0.1
          docker docker-compose up -d --build
      - run: |
        docker-compose exec specifically-sports ng test --watch=false
        docker-compose exec specifically-sports ng e2e --port 4202
      - run: docker-compose stop
workflows:
    build-and-test:
      jobs:
        - build-and-test