version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: echo 'Hello World'
workflows:
    build-and-test:
      jobs:
        - build-and-test