version: 2.1
jobs:
  build-and-test:
    machine:
      - image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: |
          VERSION=0.1
          docker-compose -f docker-compose.yml up -d --build
      - run: docker container ls
      - run: docker-compose exec specifically-sports ng test --watch=false
      - run: docker-compose exec specifically-sports ng e2e --port 4202
      - run: docker-compose stop
workflows:
    build-and-test:
      jobs:
        - build-and-test