version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: |
          VERSION=0.1
          docker build -t mmaines16/specifically-sports:0.1 .
      - run: docker image ls
workflows:
    build-and-test:
      jobs:
        - build-and-test