version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: |
          VERSION=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKER_USER/$DOCKER_TAG:$VERSION .
      - run: docker image ls
workflows:
    build-and-test:
      jobs:
        - build-and-test